DROP TABLE IF EXISTS to_do_list CASCADE;
CREATE TABLE to_do_list (
	id INT AUTO_INCREMENT,
	todo1 VARCHAR(255) NOT NULL,
	todo2 VARCHAR(255) NOT NULL,
	todo3 VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);